version: '3'

services:
  script_service:
    build: .
    image: dataprep:latest
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - ./scripts:/srv/scripts
